In [1]:
# Import the NumPy library with the alias np.
import numpy as np

In [2]:
# Create a 1D NumPy array from the Python list [1, 2, 3, 4, 5]. 
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
# Create a 1D array of 10 zeros. 
zeros_arr = np.zeros(10)
print(zeros_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Create a 3x3 array filled with ones. 
ones_arr = np.ones((3, 3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Create an array of all even integers from 10 to 50.
even_arr = np.arange(10, 51, 2)
print(even_arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
# Create a 3x3 matrix with values ranging from 0 to 8. 
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# Create a 4x4 identity matrix. 
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Create an array of 5 numbers evenly spaced between 0 and 1. 
evenly_spaced = np.linspace(0, 1, 5)
print(evenly_spaced)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
# Create a 3x4 array filled with random numbers between 0 and 1.
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.26440699 0.40246237 0.20123926 0.3729223 ]
 [0.04566978 0.35836502 0.95149545 0.16534081]
 [0.77904706 0.57419919 0.29597515 0.86348067]]


In [10]:
# Create a 5x5 array with random integers from 1 to 100.
random_int_matrix = np.random.randint(1, 101, (5, 5))
print(random_int_matrix)

[[ 38  40  70  93   8]
 [100  53  77  10  66]
 [ 26  48  31  41  46]
 [ 97  81  19  76  47]
 [ 30  87  12  18  50]]


In [11]:
# Given the array arr = np.arange(25).reshape(5, 5), find its shape. 
arr = np.arange(25).reshape(5, 5)
print(arr.shape)

(5, 5)


In [12]:
# For the same array arr, find its data type. 
arr = np.arange(25).reshape(5, 5)
print(arr.dtype)

int64


In [14]:
# For the same array arr, find the total number of elements.
arr = np.arange(25).reshape(5, 5)
print(arr.size)

25


In [15]:
#  Create the array [1, 2, 3] but make sure its data type is float.
float_arr = np.array([1, 2, 3], dtype=float)
print(float_arr)

[1. 2. 3.]


In [16]:
#  Convert the data type of an existing integer array to float. 
int_arr = np.array([10, 20, 30, 40])
float_arr = int_arr.astype(float)
print(float_arr)

[10. 20. 30. 40.]


In [17]:
arr_1d = np.arange(10)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [18]:
#  From arr_1d, get the first element.
print(arr_1d[0])

0


In [19]:
# From arr_1d, get the last element.
print(arr_1d[-1])

9


In [20]:
#  From arr_1d, get the elements from index 2 up to index 5. 
print(arr_1d[2:6])

[2 3 4 5]


In [21]:
#  From arr_1d, get all elements in reverse order.
print(arr_1d[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [22]:
# From arr_2d, get the element at row 1, column 2 (which is 6). 
print(arr_2d[1, 2])

6


In [23]:
#  From arr_2d, get the entire first row [1, 2, 3]. 
print(arr_2d[0])

[1 2 3]


In [24]:
# From arr_2d, get the entire second column [2, 5, 8].
print(arr_2d[:, 1])

[2 5 8]


In [25]:
#  From arr_2d, extract the sub-array [[1, 2], [4, 5]]. 
print(arr_2d[:2, :2])

[[1 2]
 [4 5]]


In [26]:
#  Create a boolean mask to find all numbers in arr_1d that are greater than 5. 
mask = arr_1d > 5
print(mask)

[False False False False False False  True  True  True  True]


In [27]:
# Use the boolean mask from the previous question to select the actual numbers from arr_1d. 
print(arr_1d[arr_1d > 5])

[6 7 8 9]


In [28]:
# In one line, select all numbers from arr_2d that are odd. 
print(arr_2d[arr_2d % 2 != 0])

[1 3 5 7 9]


In [29]:
#  In arr_1d, replace all values greater than 5 with the value 0. 
arr_1d[arr_1d > 5] = 0
print(arr_1d)

[0 1 2 3 4 5 0 0 0 0]


In [30]:
#  From arr_1d, select the elements at indices 1, 3, and 7. 
print(arr_1d[[1, 3, 7]])

[1 3 0]


In [31]:
# From arr_2d, select the first and third rows. 
print(arr_2d[[0, 2]])

[[1 2 3]
 [7 8 9]]


In [32]:
# What is the difference between a slice (view) and a fancy index (copy)? Modify a slice of arr_1d and see if the original changes.
# Slice (view)
slice_view = arr_1d[2:5]
slice_view[:] = 99
print("Modified slice:", slice_view)
print("Original arr_1d after slice modification:", arr_1d)

Modified slice: [99 99 99]
Original arr_1d after slice modification: [ 0  1 99 99 99  5  0  0  0  0]


In [33]:
# Create a copy of arr_2d and modify an element in the copy. Check if the original array is affected.
arr_2d_copy = arr_2d.copy()
arr_2d_copy[0, 0] = 999

print("Modified copy:\n", arr_2d_copy)
print("Original arr_2d:\n", arr_2d)

Modified copy:
 [[999   2   3]
 [  4   5   6]
 [  7   8   9]]
Original arr_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#  From arr_2d, get the diagonal elements [1, 5, 9].
print(np.diag(arr_2d))

[1 5 9]


In [36]:
# Select all rows from arr_2d where the first element is less than 5. 
print(arr_2d[arr_2d[:, 0] < 5])

[[1 2 3]
 [4 5 6]]


In [37]:
#  From arr_2d, select the elements [2, 4, 9]. 
print(arr_2d[[0, 1, 2], [1, 0, 2]])

[2 4 9]


In [38]:
#  Reverse the order of the rows in arr_2d. 
print(arr_2d[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [39]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [40]:
#  Add array a and b element-wise. 
print(a + b)

[ 6  8 10 12]


In [41]:
# Multiply array a by 3 (scalar multiplication). 
print(a * 3)

[ 3  6  9 12]


In [42]:
#  Calculate the square of every element in array a. 
print(np.square(a))

[ 1  4  9 16]


In [43]:
#  Calculate the square root of every element in b. 
print(np.sqrt(b))

[2.23606798 2.44948974 2.64575131 2.82842712]


In [44]:
# Calculate the exponential (e^x) of every element in a. 
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [45]:
# Find the sum of all elements in a. 
print(np.sum(a))

10


In [46]:
# Find the mean of all elements in b. 
print(np.mean(b))

6.5


In [47]:
# Find the maximum value in a. 
print(np.max(a))

4


In [48]:
# Find the minimum value in b.
print(np.min(b))

5


In [49]:
#  Given a 2D array matrix = np.arange(12).reshape(3, 4), find the sum of all its elements.
matrix = np.arange(12).reshape(3, 4)
print(matrix.sum())

66


In [50]:
# For the matrix, find the sum of each column.
print(matrix.sum(axis=0))

[12 15 18 21]


In [51]:
#  For the matrix, find the mean of each row. 
print(matrix.mean(axis=1))

[1.5 5.5 9.5]


In [52]:
# For the matrix, find the minimum value in each row. 
print(matrix.min(axis=1))

[0 4 8]


In [53]:
# Create a new array by finding which element is larger at each position between a and b.
print(np.maximum(a, b))

[5 6 7 8]


In [54]:
#  Round all values in the array arr_float = np.array([1.5, 2.3, 3.8]) to the nearest integer.
arr_float = np.array([1.5, 2.3, 3.8])
print(np.round(arr_float))

[2. 2. 4.]


In [55]:
# Calculate the standard deviation of array a. 
print(np.std(a))

1.118033988749895


In [56]:
#  Calculate the cumulative sum of a. The result should be [1, 3, 6, 10].
print(np.cumsum(a))

[ 1  3  6 10]


In [57]:
#  Compare arrays a and b to see if they are equal element-wise. 
print(a == b)

[False False False False]


In [58]:
# Check if any element in the result of a > 2 is True.
print((a > 2).any())

True


In [59]:
# Check if all elements in b are greater than 4. 
print((b > 4).all())

True


In [60]:
# Reshape the 1D array arr = np.arange(20) into a 4x5 matrix. 
arr = np.arange(20)
print(arr.reshape(4, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [61]:
# "Flatten" the 2D array matrix = np.array([[1,2],[3,4]]) into a 1D array.
matrix = np.array([[1, 2], [3, 4]])
print(matrix.ravel())

[1 2 3 4]


In [64]:
# What is the main difference between .ravel() and .flatten()? 
arr = np.array([[1, 2], [3, 4]])

ravel_view = arr.ravel()
flatten_copy = arr.flatten()

# Modify ravel_view
ravel_view[0] = 99

print("Original array after ravel modification:")
print(arr)

print("Flatten copy (independent):")
print(flatten_copy)

Original array after ravel modification:
[[99  2]
 [ 3  4]]
Flatten copy (independent):
[1 2 3 4]


In [65]:
# Transpose a 3x5 matrix into a 5x3 matrix.
matrix = np.arange(15).reshape(3, 5)
print(matrix.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [66]:
# Vertically stack the arrays a = np.ones((2,3)) and b = np.zeros((2,3)). 
a = np.ones((2, 3))
b = np.zeros((2, 3))
print(np.vstack((a, b)))

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [67]:
# Horizontally stack the arrays a and b.
print(np.hstack((a, b)))

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [68]:
#  Use np.concatenate to achieve the same result as vstack with a and b. 
print(np.concatenate((a, b), axis=0))

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [69]:
#  Split the array arr = np.arange(10) into 5 equal sub-arrays. 
arr = np.arange(10)
print(np.split(arr, 5))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [70]:
# Split the 2D array matrix = np.arange(16).reshape(4,4) horizontally into 2 equal arrays.
matrix = np.arange(16).reshape(4, 4)
print(np.hsplit(matrix, 2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [71]:
# Insert the value 99 at index 2 in the 1D array arr = np.array([1,2,3,4]). 
arr = np.array([1, 2, 3, 4])
print(np.insert(arr, 2, 99))

[ 1  2 99  3  4]


In [72]:
# Add the value 5 to the end of array arr. 
print(np.append(arr, 5))

[1 2 3 4 5]


In [73]:
# Get the unique values from the array arr = np.array([1,1,2,3,3,3,4,5]). 
arr = np.array([1, 1, 2, 3, 3, 3, 4, 5])
print(np.unique(arr))

[1 2 3 4 5]


In [74]:
# Repeat the array [1,2,3] three times to get [1,2,3,1,2,3,1,2,3].
arr = np.array([1, 2, 3])
print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


In [75]:
# Repeat each element of [1,2,3] three times to get [1,1,1,2,2,2,3,3,3].
print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [76]:
# Flip an array horizontally (left to right). 
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(np.fliplr(matrix))

[[3 2 1]
 [6 5 4]]


In [79]:
# Add a 1D array v = np.array([1, 2, 3]) to each row of a 2D array M = np.ones((4,3)). What is this concept called?
M = np.ones((4, 3))
v = np.array([1, 2, 3])
print(M + v)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [80]:
#  Can you add a (3,3) matrix and a (3,) vector? If so, how does it work?
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])
print(matrix + vector)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [81]:
#  Can you add a (3,3) matrix and a (3,1) matrix? 
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
col_vector = np.array([[10], [20], [30]])
print(matrix + col_vector)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [82]:
# Create a 1D array arr = np.arange(10). Use np.where to create a new array where values are 0 if the original value was less than 5, and the original value otherwise.
arr = np.arange(10)
new_arr = np.where(arr < 5, 0, arr)
print(new_arr)

[0 0 0 0 0 5 6 7 8 9]


In [83]:
# Use np.where to create a new array from arr where even numbers are replaced by 0 and odd numbers by 1.
arr = np.arange(10)
binary_arr = np.where(arr % 2 == 0, 0, 1)
print(binary_arr)

[0 1 0 1 0 1 0 1 0 1]


In [84]:
# Create a 5x5 array of random integers. Use np.where to replace all values greater than 50 with the value 50.
arr = np.random.randint(0, 100, size=(5, 5))
print("Original:\n", arr)
print("Modified:\n", np.where(arr > 50, 50, arr))

Original:
 [[27 81 30 32 84]
 [31 60 11  2  6]
 [38 39 94 78  4]
 [93 92 28 58 55]
 [98 88 35 92 44]]
Modified:
 [[27 50 30 32 50]
 [31 50 11  2  6]
 [38 39 50 50  4]
 [50 50 28 50 50]
 [50 50 35 50 44]]


In [85]:
# Create a 1D array from 1 to 10. Extract all numbers that are either less than 3 or greater than 8.
arr = np.arange(1, 11)
filtered = arr[(arr < 3) | (arr > 8)]
print(filtered)

[ 1  2  9 10]


In [86]:
# What will be the result of adding a (4,1) array to a (1,5) array? 
A = np.arange(4).reshape(4, 1)
B = np.arange(5).reshape(1, 5)
print(A + B)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [87]:
# Normalize a 5x5 random matrix (subtract the mean and divide by the standard deviation).
matrix = np.random.randint(0, 100, size=(5, 5))
mean = matrix.mean()
std = matrix.std()
normalized = (matrix - mean) / std

print("Original:\n", matrix)
print("Normalized:\n", normalized)

Original:
 [[13 65  4 78 16]
 [90 97 87 95 76]
 [96 34 41  0 21]
 [11 87 88 91 78]
 [35 77 17 23  9]]
Normalized:
 [[-1.15308342  0.33995288 -1.41149354  0.71321195 -1.06694671]
 [ 1.05775879  1.25874445  0.97162208  1.20131997  0.65578748]
 [ 1.23003221 -0.55012645 -0.3491408  -1.52634249 -0.92338552]
 [-1.21050789  0.97162208  1.00033432  1.08647103  0.71321195]
 [-0.52141421  0.68449972 -1.03823447 -0.86596105 -1.26793236]]


In [88]:
# Given a 1D array, create a 2D array where each row is a copy of the original array.
arr = np.array([1, 2, 3])
repeated = np.tile(arr, (4, 1))
print(repeated)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [89]:
# Create a 1D array of 10 random integers and sort it in ascending order. 
arr = np.random.randint(0, 100, size=10)
print("Original:", arr)
print("Sorted:", np.sort(arr))

Original: [22 94  2  8 34 96 12 62 96 35]
Sorted: [ 2  8 12 22 34 35 62 94 96 96]


In [90]:
# What is the difference between np.sort(arr) and arr.sort()?
arr = np.array([5, 2, 9, 1])
sorted_copy = np.sort(arr)
arr.sort()

print("Sorted copy:", sorted_copy)
print("In-place sorted:", arr)

Sorted copy: [1 2 5 9]
In-place sorted: [1 2 5 9]


In [91]:
# Find the indices that would sort the array arr = np.array([3, 1, 4, 2]). 
arr = np.array([3, 1, 4, 2])
print(np.argsort(arr))

[1 3 0 2]


In [92]:
# Find the index of the maximum value in arr. 
arr = np.array([3, 1, 4, 2])
print(np.argmax(arr))

2


In [93]:
# Find the index of the minimum value in arr. 
print(np.argmin(arr))

1


In [94]:
# In a 2D array, find the index of the maximum value in each column. 
matrix = np.array([[1, 5, 3],
                   [7, 2, 9],
                   [4, 8, 6]])
print(np.argmax(matrix, axis=0))

[1 2 1]


In [95]:
#  Find the unique values and their counts in the array arr = np.array([1, 2, 2, 3, 3, 3, 1]).
arr = np.array([1, 2, 2, 3, 3, 3, 1])
values, counts = np.unique(arr, return_counts=True)
print("Values:", values)
print("Counts:", counts)

Values: [1 2 3]
Counts: [2 2 3]


In [96]:
# Find the common elements between two arrays a = np.array([1,2,3]) and b = np.array([2,3,4]).
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(np.intersect1d(a, b))

[2 3]


In [97]:
# Find the elements in a that are not in b. 
print(np.setdiff1d(a, b))

[1]


In [98]:
# Sort a 2D array based on its second column.
arr = np.array([[10, 3],
                [5, 1],
                [8, 2]])
sorted_indices = np.argsort(arr[:, 1])
print(arr[sorted_indices])

[[ 5  1]
 [ 8  2]
 [10  3]]


In [99]:
# Find the 50th percentile (median) of a random array. 
arr = np.random.randint(0, 100, size=10)
print("Array:", arr)
print("Median:", np.percentile(arr, 50))

Array: [60 23 29 52 32 36 49 28 36 12]
Median: 34.0


In [100]:
#  Find the 25th and 75th percentiles of an array.
print(np.percentile(arr, [25, 75]))

[28.25 45.75]


In [101]:
# Find all non-zero elements in the array [1, 0, 2, 0, 3]. 
arr = np.array([1, 0, 2, 0, 3])
print(np.nonzero(arr))

(array([0, 2, 4]),)


In [103]:
# Check which elements of array a are present in array b.
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([2, 4])
print(np.isin(a, b))

[False  True False  True]


In [104]:
# Find the top 3 largest values from a 1D array.
arr = np.array([10, 45, 23, 67, 89, 12])
sorted_arr = np.sort(arr)
print(sorted_arr[-3:])

[45 67 89]


In [105]:
# Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication. 
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)  # OR use np.matmul(A, B)

[[19 22]
 [43 50]]


In [106]:
# Find the inverse of matrix A. 
inv_A = np.linalg.inv(A)
print(inv_A)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [107]:
# Find the determinant of matrix B. 
det_B = np.linalg.det(B)
print(det_B)

-2.000000000000005


In [110]:
# Save a NumPy array to a binary file named my_array.npy. 
# Step 1: Create a NumPy array
my_array = np.array([10, 20, 30, 40, 50])

# Step 2: Save the array to a binary file
np.save('my_array.npy', my_array)

In [111]:
loaded_array = np.load('my_array.npy')
print(loaded_array)

[10 20 30 40 50]


In [112]:
# Load the array from my_array.npy. 
loaded_array = np.load('my_array.npy')
print(loaded_array)

[10 20 30 40 50]


In [115]:
# Save a 2D array to a text file my_matrix.csv with comma-separated values. 
import numpy as np
# Step 1: Create a 2D NumPy array
my_matrix = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

# Step 2: Save the array to a CSV file with comma-separated values
np.savetxt('my_matrix.csv', my_matrix, delimiter=',', fmt='%d')

In [116]:
# Load the CSV file and print its contents
loaded_matrix = np.loadtxt('my_matrix.csv', delimiter=',', dtype=int)
print(loaded_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
